name: SonarCloud Scan - Spark

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v3

      # Configura o Node.js (opcional, só se seu projeto precisar)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Roda o SonarCloud Scan usando a nova action
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=quaghate_Spark
            -Dsonar.organization=quaghate
            -Dsonar.sources=.

